DROP DATABASE IF EXISTS ProyectoNatalia;
CREATE DATABASE ProyectoNatalia;

USE ProyectoNatalia
CREATE TABLE Obras (
    N_Registro INT,
    Titulo VARCHAR(255),
    Autor VARCHAR(255),
    Fecha_compra DATE,
    Año_compra INT,
    Valor_adquisicion FLOAT,
    Tasacion_actual FLOAT,
    Ubicacion VARCHAR(255),
    Serie VARCHAR(255),
    Edicion INT,
    Ediciones_Totales VARCHAR(255),
    CEF_Autor VARCHAR(255),
    CEF_Galeria VARCHAR(255),
    Foto_HD VARCHAR(255),
    Historial_Procedencia VARCHAR(512),
    Año INT,
    Categoria VARCHAR(255),
    Caracteristicas VARCHAR(255),
    Marco VARCHAR(255),
    Cristal VARCHAR(255),
    Firma VARCHAR(255), 
    Firma2 VARCHAR(512),
    Observaciones VARCHAR(255),
    OTROS_NOMBRES VARCHAR(255),
    Referencias VARCHAR(255),
    Proveedor VARCHAR(255),
    Embalaje VARCHAR(255),
    Mol_Obra VARCHAR(255),
    Moa_Obra VARCHAR(255),
    Mop_Obra VARCHAR(255),
    Medidas_obra VARCHAR(255),
    Mml_marco VARCHAR(255),
    Mma_marco VARCHAR(255),
    Mmp_marco VARCHAR(255),
    Medidas_con_Marco VARCHAR(255),
    MCL_embalaje VARCHAR(255),
    MCA_embalaje VARCHAR(255),
    MCP_embalaje VARCHAR(255),
    Medidas_embalaje VARCHAR(255),
    Fecha_caja INT
);



CREATE TABLE Exposiciones_Publicaciones (
    N_Registro INT,
    Expuesto VARCHAR(255),
    Catalogado VARCHAR(255),
    Tipo_2 VARCHAR(255), 
    N_exposicion INT,
    N_Publicacion VARCHAR(255),
    Año_Exp INT,
    Obra VARCHAR(255),
    Año_Obra VARCHAR(255),
    N_reg INT,
    Autor VARCHAR(255),
    libro_cat VARCHAR(255),
    ISBN VARCHAR(255),
    tipo VARCHAR(255),
    Titulo_Exp VARCHAR(512), 
    Titulo_Publi VARCHAR(255),
    Autores_Publi VARCHAR(255),
    Autores_Publi_exp VARCHAR(255),
    Comisario VARCHAR(255),
    Lote VARCHAR(255),
    Cat_N VARCHAR(255),
    Lam_ilust VARCHAR(255),
    Pag VARCHAR(255),
    Rep VARCHAR(255),
    cita VARCHAR(255),
    Indice_obra VARCHAR(255),
    Abreviada VARCHAR(255),
    Produccion VARCHAR(255),
    Imprenta VARCHAR(255),
    Desde DATE,
    Hasta DATE,
    Sala VARCHAR(255),
    Lugar VARCHAR(255)
);
